---
title: "ISA 444: Business Forecasting"
subtitle: "19 - ARIMA Models"
author: Fadel M. Megahed
date: 'Fall 2020'
output:
  beamer_presentation:
    number_sections: false
    toc: false
    slide_level: 3
    includes: 
      in_header: structure.txt
classoption: "aspectratio=169"
always_allow_html: yes
bibliography: refs.bib
link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE,
                      verbose = FALSE,
                      progress = FALSE,
                      fig.align = "center",
                      fig.pos = 'p',
                      fig.width = 5.8,
                      fig.height= 2.9,
                      allowframebreaks = TRUE,
                      fig.margin=TRUE,
                      kable.force.latex = TRUE,
                      cache = TRUE)
options(kableExtra.latex.load_packages = FALSE)
pacman::p_load(kableExtra, tidyverse, tidyquant, xtable, magrittr, fpp2, ggpubr)
```

# Preface

### Recap of What we Have Covered Last Two Classes

**ARMA Models:** Models we considered may have two components, an autoregressive component (AR) and a moving average component (MA).

\begin{block}{\textbf{Main Learning Outcomes from Last Class}}
  \begin{itemize}
      \item \textbf{Describe the behavior of the ACF and PACF of an AR(p) process.}
			\item \textbf{Describe the behavior of the ACF and PACF of an MA(q) process.}
			 \item \textbf{Describe the behavior of the ACF and PACF of an ARMA (p,q) process.}
			\item \textbf{Fit an ARMA model to a time series, evaluate the residuals of a fitted ARMA model to assess goodness of fit, use the Ljung-Box test for correlation among the residuals of an ARIMA model.}
	\end{itemize}
\end{block}


### Learning Outcomes for Today's Class
\begin{block}{\textbf{Main Learning Outcomes}}
  \begin{itemize}
      \item \textbf{Use nonseasonal differencing to attain stationarity for a time series.}
			\item \textbf{Fit an AIRMA model to a time series, evaluate the residuals of a fitted ARMA model to assess goodness of fit, use the Ljung-Box test for correlation among the residuals of an ARIMA model.}
			\item \textbf{R: Convert data into a time-series (xts insead of ts objects), and forecast future values of a time-series}
	\end{itemize}
\end{block}


# Exam 2 Walk Through

### Exam 2 Walk-Through

In class, we will go through each of the questions for Exam 2 to make sure that everyone has a good understanding of the concepts that I evaluated in Exam 2.


# ARIMA Models


### ARIMA Models for Nonstationary Processes
When the time series is nonstationary, differencing can be used to transform the series. The ADF or KPSS tests can be used to test for stationarity, and the `ndiffs()` function is useful for determining the number of differences necessary to achieve stationarity.


### A Live-Example

In class, we will use the [GNP Data](https://fred.stlouisfed.org/series/GNP) to highlight how ARIMA models can be fit and used for forecasting.


### Things to Do to Prepare for Next Class

 - Thoroughly read Chapters 6.2 of our textbook.
 
 - Go through the slides, examples and make sure you have a good understanding of what we have covered.  
 
 - **Practice:** For the file titled: [18 - inclass ARMA Practice.csv](https://miamioh.instructure.com/courses/123532/files/17704227?module_item_id=2619166), please identify: (a) whether Series 1-20, fit the appropriate ARIMA(p, d, q) model and use the `checkresiduals()` to ensure that your residuals are uncorrelated.
 


---

\maketitle