---
title: "Solutions for Graded Assignment 03"
author: "Fadel M. Megahed"
date: "8/23/2020"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    number_sections: TRUE
    theme: simplex
    paged_df: TRUE
    code_folding: show
  includes:
    in_header: "../structure.tex"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE,
                      cache = TRUE,
                      progress = FALSE, 
                      verbose = FALSE,
                      dpi = 600)
options(qwraps2_markup = "markdown")
```

# Loading the required packages
```{r packages}
if(require(pacman)==FALSE) install.packages("pacman")
pacman::p_load(tidyverse, readxl, lubridate)
```


# Plotting the Data

## Time Series Plot
```{r timeseries}
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
download.file("https://www.wessexlearning.org/pobf2e/dsa/Boulder_2.xlsx",
              destfile = "../Data/Boulder_2.xlsx", mode = "wb")
dfBoulder = read_excel("../Data/Boulder_2.xlsx")
dfBoulder$YearMonth = paste(dfBoulder$Year, dfBoulder$Month, 01, sep = "-") %>% 
  ymd()
dfBoulder %>% ggplot(aes(x = YearMonth, y = Temperature)) +
  geom_line() + geom_point() +
  labs(title = "Scatterplot of Temperature vs. Time",
       caption = "Data from Ord et al. (2017)") + theme_bw()
```

```{r seasonal}
dfBoulder %>% filter(Year >= 2012) %>% 
  ggplot(aes(x = month(YearMonth), y = Temperature, 
                         group = Year, color = as.factor(Year))) +
  geom_line() + geom_point() +
  labs(title = "Seasonal Plot of Temperature vs. Time",
       caption = "Data from Ord et al. (2017)",
       color = "Year") + theme_bw()
```

# Summarizing the Data

```{r summary, results='asis'}
print(paste("The overall standard deviation for the Temperature variable for the entire dataset is equal to", dfBoulder$Temperature %>% sd() %>% round(2) ))

dfBoulder %>% group_by(Month) %>% summarise(sd = sd(Temperature) %>% round(2) ) %>% 
  DT::datatable() # last command just for printing
```